
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FBF.Service.DBService
{

using System;
    using System.Collections.Generic;
    
public partial class Comment
{

    public long CommentId { get; set; }

    public string Name { get; set; }

    public Nullable<long> ForumId { get; set; }

    public Nullable<System.DateTime> Createon { get; set; }

    public Nullable<bool> IsActive { get; set; }

    public Nullable<long> UserId { get; set; }



    public virtual Forum Forum { get; set; }

    public virtual tblUser tblUser { get; set; }

}

}
