
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FBF.Service.DBService
{

using System;
    using System.Collections.Generic;
    
public partial class tblBlogComment
{

    public long ID { get; set; }

    public Nullable<long> BlogID { get; set; }

    public Nullable<long> CustomerID { get; set; }

    public string Comment { get; set; }

    public Nullable<System.DateTime> Date { get; set; }



    public virtual tblBlog tblBlog { get; set; }

    public virtual tblUser tblUser { get; set; }

}

}
