
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FBF.Service.DBService
{

using System;
    using System.Collections.Generic;
    
public partial class tblUser
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblUser()
    {

        this.Comments = new HashSet<Comment>();

        this.Fora = new HashSet<Forum>();

        this.tblBlogs = new HashSet<tblBlog>();

        this.tblBlogComments = new HashSet<tblBlogComment>();

    }


    public long ID { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string UserID { get; set; }

    public string Email { get; set; }

    public string Passworrd { get; set; }

    public Nullable<bool> IsAdmin { get; set; }

    public Nullable<bool> IsAthlete { get; set; }

    public string DocumentFile { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public Nullable<int> StatusID { get; set; }



    public virtual tblStatu tblStatu { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Comment> Comments { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Forum> Fora { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblBlog> tblBlogs { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblBlogComment> tblBlogComments { get; set; }

}

}
